---
签到.单次.金钱: 30
签到.累计天数.开启: true
签到.累计天数.金钱: 2
签到.累计天数.上限: 30
签到.进入提示.是否开启: true
签到.VIP加成.是否开启: true
签到.VIP插件.名称: rvip
签到.VIP加成.倍数: 1.500000
签到.单次.随机金钱.开启: false
签到.单次.随机金钱.最小值: 10
签到.单次.随机金钱.最大值: 30
...
